sudo: required

language: ruby

services:
  - docker

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build . -t macbootglass/myownportfolio-core

deploy:
  provider: script
  script: docker push macbootglass/myownportfolio-core:latest
