sudo: required

services:
  - docker

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build . -t macbootglass/myownportfolio-core

deploy:
  - docker push macbootglass/myownportfolio-core:latest
