const fs = require('fs');

const pwd = process.cwd();
const src = "/app/modules";
const dist = "/docs/json_schema/import.js";

const schemas_name = [
  "content.json",
  "properties.json",
  "style.json"
];

var schemas = [];

fs.readdir(pwd + src, (err, modules_list) => {
  for (var i=0; i < modules_list.length; i++) {
    for (var j=0; j < schemas_name.length; j++) {
      schemas.push(require(pwd + src + '/' + modules_list[i] + '/json_schema/' + schemas_name[j]));
    }
  }

  var output = '// AUTOGENERATED FROM myOwnPortfolio/tools/node/generate_doc\n';
  output += 'module.exports = ' + JSON.stringify({
    "schemas_name": schemas_name,
    "modules": modules_list,
    "schemas": schemas
  });


  fs.writeFile(pwd + dist, output, function(err) {
    if(err) {
      throw new Error(err);
    }
    console.log("Script import.js généré");
  });
});
