const fs = require('fs');

const pwd = process.cwd();
const src = "/app/modules";
const dist = "/docs/json_schema/import.js";

const schemas_name = [
  "content.json",
  "properties.json",
  "style.json"
];

var schemas = [];

fs.readdir(pwd + src, (err, modules_list) => {
  schemas.push(require(pwd + "/app/config/modules_list_schema"));
  schemas[schemas.length-1].group = "modules_list";

  schemas.push(require(pwd + "/app/config/app_properties_schema"));
  schemas[schemas.length-1].group = "app_properties";

  for (var i=0; i < modules_list.length; i++) {
    for (var j=0; j < schemas_name.length; j++) {
      schemas.push(require(pwd + src + '/' + modules_list[i] + '/json_schema/' + schemas_name[j]));
      schemas[schemas.length-1].group = modules_list[i];
    }
  }

  var output = '// AUTOGENERATED FROM myOwnPortfolio/tools/node/generate_doc.js\n';
  output += 'module.exports = ' + JSON.stringify({
    "schemas_name": schemas_name,
    "modules": modules_list,
    "schemas": schemas
  });


  fs.writeFile(pwd + dist, output, function(err) {
    if(err) {
      throw new Error(err);
    }
    console.log("Script import.js généré");
  });
});
